export const ADMIN_BOARDS_GET_REQUEST = "ADMIN_BOARDS_GET_REQUEST";
export const ADMIN_BOARDS_GET_SUCCESS = "ADMIN_BOARDS_GET_SUCCESS";
export const ADMIN_BOARDS_GET_FAILURE = "ADMIN_BOARDS_GET_FAILURE";

export const ADMIN_TASK_GET_REQUEST = "ADMIN_TASK_GET_REQUEST";
export const ADMIN_TASK_GET_SUCCESS = "ADMIN_TASK_GET_SUCCESS";
export const ADMIN_TASK_GET_FAILURE = "ADMIN_TASK_GET_FAILURE";

export const ADMIN_TASK_DELETE_REQUEST = "ADMIN_TASK_DELETE_REQUEST";
export const ADMIN_TASK_DELETE_SUCCESS = "ADMIN_TASK_DELETE_SUCCESS";
export const ADMIN_TASK_DELETE_FAILURE = "ADMIN_TASK_DELETE_FAILURE";

export const ADMIN_TASK_UPDATE_REQUEST = "ADMIN_TASK_UPDATE_REQUEST";
export const ADMIN_TASK_UPDATE_SUCCESS = "ADMIN_TASK_UPDATE_SUCCESS";
export const ADMIN_TASK_UPDATE_FAILURE = "ADMIN_TASK_UPDATE_FAILURE";


