export const TASK_CREATION_REQUEST = "TASK_CREATION_REQUEST";
export const TASK_CREATION_SUCCESS = "TASK_CREATION_SUCCESS";
export const TASK_CREATION_FAILURE = "TASK_CREATION_FAILURE";

export const TASK_GET_REQUEST = "TASK_GET_REQUEST";
export const TASK_GET_SUCCESS = "TASK_GET_SUCCESS";
export const TASK_GET_FAILURE = "TASK_GET_FAILURE";

export const TASK_UPDATE_REQUEST = "TASK_UPDATE_REQUEST";
export const TASK_UPDATE_SUCCESS = "TASK_UPDATE_SUCCESS";
export const TASK_UPDATE_FAILURE = "TASK_UPDATE_FAILURE";


