export const BOARD_CREATION_REQUEST = "BOARD_CREATION_REQUEST";
export const BOARD_CREATION_SUCCESS = "BOARD_CREATION_SUCCESS";
export const BOARD_CREATION_FAILURE = "BOARD_CREATION_FAILURE";

export const BOARD_GET_REQUEST = "BOARD_GET_REQUEST";
export const BOARD_GET_SUCCESS = "BOARD_GET_SUCCESS";
export const BOARD_GET_FAILURE = "BOARD_GET_FAILURE";
